name: Create Release Assets

on:
  push:
    branches:
      - 'master'

jobs:
  buildrpms:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:43

    steps:
      - name: Clone code
        uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          dnf install -y rpmdevtools rpm-sign rpkg python3-setuptools 'dnf-command(builddep)'
          dnf builddep -y ./iptsd.spec

      - name: Prepare build
        run: |
          cat <<EOT > ./rpkg.conf
          [rpkg]
          user_macros = "/__w/iptsd/iptsd/rpkg.macros"
          EOT

          cat ./rpkg.conf

      - name: Make build
        env:
         git_props_root: "/__w/iptsd/iptsd"
        run: |
          mkdir rpm
          rpkg local --outdir "$(pwd)/rpm"
          ls ./rpm

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version="$(grep -i '^Version:' iptsd.spec |  awk '{print $2}')"
          gh release create "$version" -t "$version" --repo="${{ github.repository }}" --target="${{ github.sha }}" --generate-notes ./rpm/*.src.rpm ./rpm/x86_64/*.rpm

      - name: Install copr-cli
        run: dnf install copr-cli -y

      - name: Add login to copr
        run: |
          echo "${{ secrets.COPR_CREDENTIALS }}" >> "./coprConfig"

      - name: Upload to COPR
        run: copr-cli --config "./coprConfig" build LinuxSurface ./rpm/*.src.rpm
